!DROP TABLE notice;
SELECT * FROM notice;

CREATE TABLE notice(
   num			BIGINT				PRIMARY KEY  AUTO_INCREMENT,
   title		VARCHAR(50)			NOT NULL,
   writer		VARCHAR(50),
   content		VARCHAR(1000)		NOT NULL,
   readCnt		INT,
   regDate		TIMESTAMP			DEFAULT CURRENT_TIMESTAMP
);